# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Inicia banco
      run: docker compose up -d postgres

    - name: Aguardando postgres ficar disponível
      run: |
        echo "Aguardando Postgres iniciar..."
        until docker compose exec postgres pg_isready -U root; do
          echo "Ainda não está pronto..."
          sleep 2
        done
        echo "Postgres pronto!"

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.1
        args: controllers/ database/ models/ routes/

    - name: Test
      run: docker compose run --rm \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            test go test -v main_test.go
